---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    type: local
    env: dev
    tier: database
spec:
  accessModes:
    - ReadWriteOnce                  # Monté en lecture/écriture par un seul nœud
  storageClassName: manual           # Doit correspondre à celui du PVC
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: local